[package]
name = "dict-generate"
version = "0.9.0"
edition = "2021"

[dependencies]
opencc-fmmseg = { path = "../.." }
clap = "4.5.58"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rustc-hash = "2.1.1"

[build-dependencies]
winres = "0.1.12"