[package]
name = "opencc-clip"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencc-fmmseg = {path = "../.."}
copypasta = "0.10.2"
clap = "4.5.60"
#smithay-clipboard = "=0.7.2"